# Generated by Django 4.0.2 on 2022-02-08 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.TextField(max_length=200)),
                ('balance', models.TextField(blank=True, null=True)),
                ('percentage', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
